ALTER TABLE ATTACHMENT DROP FOREIGN KEY FK_ATTACHMENT_POST_IDX
ALTER TABLE CATEGORY DROP FOREIGN KEY FK_CATEGORY_p_category_code
ALTER TABLE POST DROP FOREIGN KEY FK_POST_CATEGORY_CODE
DROP TABLE ATTACHMENT
DROP TABLE CATEGORY
DROP TABLE POST
